### ISSUE TITLE
Use of polygons

### ISSUE THREAD

**Issue by abdelzaro** [bmmeijers/quadtree#2]
Is there a reason the quadtree is represented by a polygon with 5 vertices rather than just a rectangle?  For example in this screenshot self is a polygon:
![image](https://user-images.githubusercontent.com/76800333/209691247-80d60208-61dc-44d6-b079-2debba305e4c.png)

**Comment by bmmeijers** [comment]
It is not like that: center/size tuples define the nodes their extent. 

You are looking at a `__str__` representation in your editor (which gives a WKT version - a common format for geometry in GIS - with first point of ring repeated as last point: explicitly closed).

**Comment by abdelzaro** [comment]
Oh okay, thank you. So if I want to illustrate the quadtree in pygame rather than with WKT, do you think it is okay if self is still a Polygon? As shown in the screenshot I sent earlier.

**Comment by bmmeijers** [comment]
The type of self is never a polygon, you are looking at a `str` object.

Simplest solution I guess: instantiate a pygame.Rect object for each quadtree (leaf) node. This can then be used for your purpose of visualization.

**Comment by abdelzaro** [comment]
okay, thank you!
