### ISSUE TITLE
point on border

### ISSUE THREAD

**Issue by andrewwawa** [bmmeijers/quadtree#4]
Hi, 
what does the code do if the point it wants to insert into the quadtree is on the quadtree border/boundary? How does it know which cell to place it in?

**Comment by bmmeijers** [comment]
The quadrant method determines that behaviour.

**Comment by andrewwawa** [comment]
I was looking at that function but I was not sure if a point is on the border/boundary, such as this case
![image](https://user-images.githubusercontent.com/121821983/213585790-afa03131-fb09-422c-92cd-42f949e2679c.png)

does it place the point in both the left and right quadtree cells? Does this mean these are duplicate points?

**Comment by bmmeijers** [comment]
> Does this mean these are duplicate points?

I hope not ;-)

What does make you think it would (as the interval is split in exactly two parts by the quadrant method: `point[n] >= center[n]`)?

**Comment by andrewwawa** [comment]
Okay thank you
